version: '3.8'

services:
  # 1. EUREKA
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # 2. MICROSERVICIO DE MASCOTAS
  ms-gestion-mascotas:
    build: ./gestion-mascotas
    container_name: ms-gestion-mascotas
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  # 3. API GATEWAY
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server


  # 4. Geolocalización
  ms-geolocalizacion:
    build: ./ms-geolocalizacion
    container_name: ms-geolocalizacion
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
  # 5. Coincidencias
  ms-motor-coincidencias:
    build: ./ms-motor-coincidencias
    container_name: ms-motor-coincidencias
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
  # 6. Usuarios
  ms-usuarios:
    build: ./usuarios
    container_name: ms-usuarios
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
  # 7. BFF
  ms-bff:
    build: ./ms-bff
    container_name: ms-bff
    ports:
      - "8087:8087" # puerto 8086 para ms-notificaciones
    environment:
      - SPRING_APPLICATION_NAME=ms-bff
      - SERVER_PORT=8087
      - SERVICES_MASCOTAS_URL=http://ms-gestion-mascotas:8081
      - SERVICES_GEOLOCALIZACION_URL=http://ms-geolocalizacion:8082
    depends_on:
      - ms-gestion-mascotas
      - ms-geolocalizacion