
-- 1. Crear bases de datos para cada microservicio

CREATE DATABASE db_usuarios;
CREATE DATABASE db_mascotas;
CREATE DATABASE db_notificaciones;
CREATE DATABASE db_geolocalizacion;
CREATE DATABASE db_coincidencias;


-- Sección de creación de tablas e inserción de datos para cada microservicio

-- Usuarios

\c db_usuarios;

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(255) UNIQUE NOT NULL,
    direccion VARCHAR(255),
    edad INTEGER NOT NULL CHECK (edad <= 100 AND edad >= 18),
    foto_url VARCHAR(255),
    genero VARCHAR(255) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    ocupacion VARCHAR(255),
    telefono VARCHAR(255) NOT NULL,
    session_id VARCHAR(255),
    password VARCHAR(255),
    tipo_usuario VARCHAR(100)
);

INSERT INTO usuarios 
(id, correo, direccion, edad, foto_url, genero, nombre, ocupacion, telefono, session_id, password, tipo_usuario) 
VALUES
(4, 'ma@test.com', 'sucasa', 21, 'https://img.com/foto.jpg', 'Binario', 'Mayckol', 'Estudiante', '1231231', NULL, '$2a$10$BQbOsR5odkqx35zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'cliente'),
(5, 'ni@test.com', 'Avenida mirador', 24, 'https://img.com/', 'Masculino', 'Nicolas', 'Estudiante', '1231231', '68d90d98-0293-4118-9dd0-000000000000', '$2a$10$4q.i5zv/UTLZZdiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'admin'),
(6, 'ro.vargas@duocuc.cl', 'xddd', 27, 'img.com', 'Masculino', 'Rodrigo', 'Estudiante', '123123123', NULL, '$2a$10$/Ziy7W/APEUdZDeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'cliente');

-- Actualizamos el contador de IDs para que el próximo usuario registrado sea el ID 7
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), (SELECT MAX(id) FROM usuarios));


-- Mascotas
\c db_mascotas;


CREATE TABLE reportes_mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color VARCHAR(255) NOT NULL,
    email_contacto VARCHAR(255),
    especie VARCHAR(255) NOT NULL,
    fecha_reporte TIMESTAMP,
    fotografia_url VARCHAR(255),
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION,
    nombre VARCHAR(255),
    nombre_contacto VARCHAR(255) NOT NULL,
    raza VARCHAR(255),
    tamano VARCHAR(255),
    telefono_contacto VARCHAR(255) NOT NULL,
    tipo_reporte VARCHAR(255) NOT NULL,
    saga_status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    usuario_id BIGINT NOT NULL DEFAULT 1
);


INSERT INTO reportes_mascotas
(id, color, email_contacto, especie, fecha_reporte, fotografia_url, latitud, longitud, nombre, nombre_contacto, raza, tamano, telefono_contacto, tipo_reporte, saga_status, usuario_id)
VALUES
    (1, 'Café con manchas', 'rodrigo@ejemplo.cl', 'Perro', '2026-03-28 04:15:12', 'http://img.com/perrito.jpg', -41.4689, -72.9411, 'Cachupín', 'Rodrigo', 'Quiltro Chileno', 'Mediano', '+56912345678', 'PERDIDA', 'FAILED_SYNC', 1),
    (3, 'Blanco con manchas', NULL, 'Perro', '2026-03-29 00:43:05', NULL, -41.47, -72.95, NULL, 'Maria', 'Poodle', 'Pequeño', '456', 'ENCONTRADA', 'PENDING', 1),
    (4, 'Negro', NULL, 'Perro', '2026-03-29 01:52:01', NULL, -41.48, -72.96, NULL, 'Pedro', 'Poodle', 'Pequeño', '789', 'ENCONTRADA', 'PENDING', 1),
    (5, 'Negro', 'nico@test.com', 'Perro', '2026-04-01 01:19:16', 'http://foto.com/perro.jpg', -41.47, -72.94, 'Max', 'Nicolas', 'Labrador', 'Grande', '123456789', 'PERDIDA', 'PENDING', 1),
    (6, 'Negro', 'nico@test.com', 'Perro', '2026-04-07 20:25:52', 'http://foto.com/perro.jpg', -41.47, -72.94, 'Max', 'Nicolas', 'Labrador', 'Grande', '123456789', 'PERDIDA', 'PENDING', 1),
    (7, 'Dorado', 'juan.perez@email.com', 'Perro', '2026-04-22 21:37:37', 'https://mi-storage.com/foto1.jpg', -34.6037, -58.3816, 'Toby', 'Juan Pérez', 'Golden Retriever', 'Grande', '+56912345678', 'PERDIDA', 'COMPLETED', 1),
    (8, 'Dorado', 'juan.perez@email.com', 'Perro', '2026-04-22 21:37:46', 'https://mi-storage.com/foto2.jpg', -34.6037, -58.3816, 'Toby', 'Juan Pérez', 'Golden Retriever', 'Grande', '+56912345678', 'PERDIDA', 'COMPLETED', 1),
    (9, 'Blanco', 'ro.vargas@duocuc.cl', 'Perro', '2026-05-04 18:45:20', 'https://img.com/poodle.jpg', -33.46, -70.68, 'Pelusa', 'Rodrigo', 'Poodle', 'Mediano', '123123123', 'PERDIDA', 'COMPLETED', 6),
    (10, 'Blanco Crema', 'ma@test.com', 'Gato', '2026-05-04 18:45:50', 'https://img.com/siames.jpg', -33.45, -70.67, 'Luna', 'Mayckol', 'Siames', 'Pequeño', '1231231', 'PERDIDA', 'COMPLETED', 4),
    (11, 'Dorado', 'ni@test.com', 'Perro', '2026-05-04 18:49:16', 'https://img.com/golden.jpg', -33.4489, -70.6693, 'Simba', 'Nicolas', 'Golden Retriever', 'Grande', '1231231', 'PERDIDA', 'COMPLETED', 5),
    (12, 'Dorado', 'ma@test.com', 'Perro', '2026-05-04 18:49:45', 'https://img.com/golden.jpg', -33.45, -70.67, 'Rocky', 'Mayckol', 'Golden Retriever', 'Mediano', '1231231', 'PERDIDA', 'COMPLETED', 4),
    (13, 'Dorado', 'ro.vargas@duocuc.cl', 'Perro', '2026-05-04 18:49:59', 'https://img.com/perro2.jpg', -33.448, -70.669, NULL, 'Rodrigo', 'Golden Retriever', 'Grande', '123123123', 'ENCONTRADA', 'COMPLETED', 6),
    (14, 'Blanco Crema', 'ni@test.com', 'Gato', '2026-05-04 18:54:52', 'https://img.com/siames2.jpg', -33.45, -70.67, 'Michi', 'Nicolás', 'Siames', 'mediano', '1231231', 'PERDIDA', 'COMPLETED', 5),
    (15, 'Blanco Crema', 'ro.vargas@duocuc.cl', 'Gato', '2026-05-05 19:02:41', 'https://img.com/siames3.jpg', -33.448, -70.669, NULL, 'Rodrigo', 'Siames', 'mediano', '123123123', 'ENCONTRADA', 'COMPLETED', 5),
    (16, 'Crema y Café', 'juan@test.com', 'Gato', '2026-05-06 22:05:41', 'http://foto.com/gato.jpg', -41.48, -72.95, 'Garfield', 'Juan Pérez', 'Siamés', 'Mediano', '987654321', 'PERDIDA', 'COMPLETED', 1),
    (17, 'Crema y Café', 'juan@test.com', 'Gato', '2026-05-06 22:06:09', 'http://foto.com/gato2.jpg', -41.48, -72.95, 'Garfield', 'Juan Pérez', 'Siamés', 'Mediano', '987654321', 'PERDIDA', 'COMPLETED', 2);


SELECT setval(pg_get_serial_sequence('reportes_mascotas', 'id'), (SELECT MAX(id) FROM reportes_mascotas));

-- Notificaciones

\c db_notificaciones;

CREATE TABLE notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_usuario VARCHAR(255),
    fecha_creacion TIMESTAMP,
    fotografia_url VARCHAR(255),
    leido BOOLEAN NOT NULL,
    mensaje VARCHAR(255),
    porcentaje_similitud DOUBLE PRECISION,
    reporte_id BIGINT,
    titulo VARCHAR(255),
    usuario_id BIGINT
);

INSERT INTO notificaciones 
(id, email_usuario, fecha_creacion, fotografia_url, leido, mensaje, porcentaje_similitud, reporte_id, titulo, usuario_id) 
VALUES
(5, 'ni@test.com', '2026-05-06 22:15:35.82', 'https://img.com/siames2.jpg', TRUE, 'Hay un match del 100.0%', 100, 14, '¡Posible coincidencia encontrada!', 5);

SELECT setval(pg_get_serial_sequence('notificaciones', 'id'), (SELECT MAX(id) FROM notificaciones));

-- Geolocalización

\c db_geolocalizacion;

CREATE TABLE ubicaciones_alertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_registro TIMESTAMP,
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION,
    reporte_id BIGINT,
    tipo_alerta VARCHAR(255)
);

INSERT INTO ubicaciones_alertas 
(id, fecha_registro, latitud, longitud, reporte_id, tipo_alerta) 
VALUES
(3, '2026-03-29 00:43:06.02', -41.47, -72.95, 3, 'ENCONTRADA'),
(4, '2026-03-29 01:52:03.24', -41.48, -72.96, 4, 'ENCONTRADA'),
(5, '2026-04-01 01:19:18.11', -41.47, -72.94, 5, 'PERDIDA'),
(6, '2026-04-07 20:25:59.50', -41.47, -72.94, 6, 'PERDIDA'),
(7, '2026-04-22 21:37:43.03', -34.6037, -58.3816, 7, 'PERDIDA'),
(8, '2026-04-22 21:37:46.99', -34.6037, -58.3816, 8, 'PERDIDA'),
(9, '2026-05-04 18:45:22.03', -33.46, -70.68, 9, 'PERDIDA'),
(10, '2026-05-04 18:45:51.39', -33.45, -70.67, 10, 'PERDIDA'),
(11, '2026-05-04 18:49:17.23', -33.4489, -70.6693, 11, 'PERDIDA'),
(12, '2026-05-04 18:49:46.25', -33.45, -70.67, 12, 'PERDIDA'),
(13, '2026-05-04 18:49:59.99', -33.448, -70.669, 13, 'ENCONTRADA'),
(14, '2026-05-05 18:54:53.48', -33.45, -70.67, 14, 'PERDIDA'),
(15, '2026-05-05 19:02:41.88', -33.448, -70.669, 15, 'ENCONTRADA'),
(16, '2026-05-06 22:05:42.07', -41.48, -72.95, 16, 'PERDIDA'),
(17, '2026-05-06 22:06:09.69', -41.48, -72.95, 17, 'PERDIDA');

SELECT setval(pg_get_serial_sequence('ubicaciones_alertas', 'id'), (SELECT MAX(id) FROM ubicaciones_alertas));

