server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ruta-mascotas
              uri: lb://ms-gestion-mascotas
              predicates:
                - Path=/api/mascotas/**
            - id: ms-geolocalizacion
              uri: lb://ms-geolocalizacion 
              predicates:
                - Path=/api/geolocalizacion/**
            - id: ms-motor-coincidencias
              uri: lb://ms-motor-coincidencias
              predicates:
                - Path=/api/coincidencias/**
            - id: ms-usuarios
              uri: lb://ms-usuarios
              predicates:
                - Path=/api/usuarios/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "Mascotas"
        url: /api/mascotas/v3/api-docs