server:
  port: 8086

spring:
  application:
    name: ms-notificaciones

  # CONFIGURACIÓN DE DATASOURCE, utilizando variables de entorno para mayor flexibilidad y seguridad
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_notificaciones}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  # CONFIGURACIÓN DE JPA, para que Hibernate gestione automáticamente las tablas y utilice el dialecto correcto para PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#  CONFIGURACIÓN DE EUREKA CLIENT, para que el microservicio se registre correctamente en el servidor de descubrimiento
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# CONFIGURACIÓN DE SPRINGDOC PARA LA DOCUMENTACIÓN DE LA API, con opciones para mejorar la experiencia de uso de Swagger UI
springdoc:
  show-actuator: true 
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api/notificaciones/v3/api-docs