server:
  port: 8085

jwt:
  secret: "MiClaveSuperSecretaParaMascotas123456789!"

spring:
  application:
    name: ms-usuarios

  # CONFIGURACIÓN DE DATASOURCE, utilizando variables de entorno para mayor flexibilidad y seguridad
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_usuarios}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}

  # CONFIGURACIÓN DE JPA, para que Hibernate gestione automáticamente las tablas y utilice el dialecto correcto para PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  # CONFIGURACIÓN DE CACHÉ Y REDIS
  cache:
    type: redis
    redis:
      time-to-live: 15m
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
# CONFIGURACIÓN DE EUREKA CLIENT, para que el microservicio se registre correctamente en el servidor de descubrimiento
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# CONFIGURACIÓN DE SPRINGDOC PARA LA DOCUMENTACIÓN DE LA API, con opciones para mejorar la experiencia de uso de Swagger UI
springdoc:
  show-actuator: true
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api/usuarios/v3/api-docs